before_script:
    - apt-get update -qq && apt-get install odb libodb-dev libodb-sqlite-2.4 libodb-boost-2.4
    
stages:
    - build
    - test
    
build:
    script:
    - mkdir build && cd build
    - cmake ..
    - make -j8
    
test:
    script:
    - make test