version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run: apt-get update -qq
      - run: apt-get install -y -qq odb libodb-dev libodb-sqlite-2.4 libodb-boost-2.4 libsqlite3-dev
      - run: apt-get install -y -qq g++ cmake
      - run: apt-get install -y -qq libboost-all-dev
      - run: apt-get install -y -qq pkg-config
      - run: apt-get install -y -qq libsoprano-dev
      - run: apt-get install -y -qq qt4-default
      - run: apt-get install -y -qq libgeos-dev
      - run: git clone https://github.com/OSGeo/gdal.git -b tags/2.2.3
      - run: cd gdal/gdal && ./configure -with-geos=yes
      - run: cd gdal/gdal && make -j8
      - run: cd gdal/gdal && make install
      - run: mkdir build
      - run: cd build && cmake .. && make -j8
      - run: cd build && ./test/sempr_test_bin
