version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    environment:
      LD_LIBRARY_PATH=/usr/local/lib
    steps:
      - checkout
      - run: apt-get update -qq
      - run: apt-get install -y -qq odb libodb-dev libodb-sqlite-2.4 libodb-boost-2.4 libsqlite3-dev
      - run: apt-get install -y -qq g++ cmake
      - run: apt-get install -y -qq libboost-all-dev
      - run: apt-get install -y -qq pkg-config
      - run: apt-get install -y -qq libsoprano-dev
      - run: apt-get install -y -qq qt4-default
      - run: apt-get install -y -qq libgeos-dev
      - run: apt-get install -y -qq libeigen3-dev
      - run: apt-get install -y -qq git
      - run: apt-get install -y -qq libproj0
      - restore_cache:
          keys:
            - gdal-2.2.3-cache
      - run:
          name: Install GDAL
          command: |
            git clone https://github.com/OSGeo/gdal.git -b tags/2.2.3 || echo "gdal repo already present"
            cd gdal/gdal 
            ./configure -with-geos=yes
            make -j8
            make install
      - save_cache:
          key: gdal-2.2.3-cache
          paths:
            - gdal
      - run: mkdir build
      - run: echo $LD_LIBRARY_PATH
      - run: cd build && cmake .. && make -j8
      - run: ldd build/test/sempr_test_bin | grep gdal
      - run: cd build && ./test/sempr_test_bin
